apiVersion: v2
name: pagopa-decoupler-chart
description: pagoPA Decoupler
type: application
version: "0.7.0"
appVersion: "0.0.3"
dependencies:
  - name: microservice-chart
    version: 7.1.1
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
